[package]
name = "cao-application"
description = "Tracetide application orchestration and inward-facing ports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
build = false

[dependencies]
cao-domain.workspace = true
crossbeam-channel.workspace = true

[lib]
name = "cao_application"
path = "src/lib.rs"

