[package]
name = "cao-platform-windows"
description = "Windows platform effects for Tracetide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
build = false

[dependencies]
cao-application.workspace = true

[lib]
name = "cao_platform_windows"
path = "src/lib.rs"

